### ISSUE TITLE
general design cleanup

### ISSUE THREAD

**Issue by skippy** [sjifire/website#69]
a placeholder for general design tweaks and cleanup:
* sprites
* abnormalities in design layout 
* ???

**Comment by icegulch** [comment]
I have an SVG sprite in there, but I think we're only using one of the icons so far. I think that will change. The SVG sprite is nice because it gets compressed as part of HTML minification and is served inline (not as a request).

Regardless, on the whole, it's a good time to step back and re-assess. This is where knowing what the models will be helps inform what's a css component and what's just a one-off.

**Comment by skippy** [comment]
I'm going to close this as we've made a lot of progress on this!
